name: Vercel Preview Deployment
env:
  # VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  # JUST A RANDOM COMMENT
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - master
jobs:
  Deploy-Preview:
    environment: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: confirm token
        run: |
          echo "token below"
          echo ${{secrets.VERCEL_TOKEN}}
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
